server:
  port: 8087
spring:
  datasource:
    url: jdbc:mysql://192.168.10.133:3306/dkm_game?useUnicode=true&useSSL=false&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: kgdatj1110
    driver-class-name: com.mysql.cj.jdbc.Driver
  # HTTP ENCODING
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
mybatis-plus:
  mapper-locations: classpath:com.dkm.demo.dao.mapper/*.xml

app:
  workerId: 1
  dataCenterId: 2
